spring:
  activiti:
     check-process-definitions: false #自动检查、部署流程定义文件
     database-schema-update: true
     process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
  datasource:
    url: jdbc:mysql://119.23.74.131:3306/activiti1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: FFFFFREWRET%GFHGJ23243dsdsf
    driver-class-name: com.mysql.jdbc.Driver
#logging:
#  level:
#    root: debug